sudo: false
cache: pip
language: python
python:
    - 3.6

install: 
  - pip install -r requirements-dev.txt
  - pip install codecov

script:
  - make lint
  - make ci-test

branches:
  only:
    - master

after_success:
  - codecov